# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_REPOSITORY: "adrianonsilva"
  DOCKER_IMAGE: "demo-app"

jobs:
  build-java-app:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build      

    - name: Generate sha # to use as tag on image
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT

    - name: Build and push image
      uses: docker/setup-docker-action@v4.3.0

    - name: Build docker image
      run: docker build -t $DOCKER_REPOSITORY/demo-app:${{ steps.generate_sha.outputs.sha }} .

    - name: Log into the container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Push image
      run: |
        docker push $DOCKER_REPOSITORY/DOCKER_IMAGE:${{ steps.generate_sha.outputs.sha }}
        docker tag $DOCKER_REPOSITORY/DOCKER_IMAGE:${{ steps.generate_sha.outputs.sha }} $DOCKER_REPOSITORY/DOCKER_IMAGE:latest
        docker push $DOCKER_REPOSITORY/DOCKER_IMAGE:latest

#    - name: Build and Push Docker Image
#      uses: MaximilianoBz/dockerhub-buildpush@v1.1
#      with:
#        registry_url: docker.io
#        repository_name: adrianonsilva/demo-app-java
#        user_name: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_TOKEN }}   
#        image_version: latest
#        docker_file: .